// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pm.Data;

#nullable disable

namespace Pm.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250924062820_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Pm.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Group")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionName")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(407),
                            Description = "View all users",
                            Group = "User",
                            PermissionName = "user.view-any"
                        },
                        new
                        {
                            PermissionId = 2,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(978),
                            Description = "View user detail",
                            Group = "User",
                            PermissionName = "user.view"
                        },
                        new
                        {
                            PermissionId = 3,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(982),
                            Description = "Create new user",
                            Group = "User",
                            PermissionName = "user.create"
                        },
                        new
                        {
                            PermissionId = 4,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(985),
                            Description = "Update user",
                            Group = "User",
                            PermissionName = "user.update"
                        },
                        new
                        {
                            PermissionId = 5,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(992),
                            Description = "Delete user",
                            Group = "User",
                            PermissionName = "user.delete"
                        },
                        new
                        {
                            PermissionId = 6,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(995),
                            Description = "View all roles",
                            Group = "Role",
                            PermissionName = "role.view-any"
                        },
                        new
                        {
                            PermissionId = 7,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(998),
                            Description = "View role detail",
                            Group = "Role",
                            PermissionName = "role.view"
                        },
                        new
                        {
                            PermissionId = 8,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(1002),
                            Description = "Create new role",
                            Group = "Role",
                            PermissionName = "role.create"
                        },
                        new
                        {
                            PermissionId = 9,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(1014),
                            Description = "Update role",
                            Group = "Role",
                            PermissionName = "role.update"
                        },
                        new
                        {
                            PermissionId = 10,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(1017),
                            Description = "Delete role",
                            Group = "Role",
                            PermissionName = "role.delete"
                        },
                        new
                        {
                            PermissionId = 11,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(1020),
                            Description = "View permissions",
                            Group = "Permission",
                            PermissionName = "permission.view"
                        },
                        new
                        {
                            PermissionId = 12,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(1023),
                            Description = "Edit permissions",
                            Group = "Permission",
                            PermissionName = "permission.edit"
                        });
                });

            modelBuilder.Entity("Pm.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 11, DateTimeKind.Utc).AddTicks(1068),
                            Description = "Full system access",
                            IsActive = true,
                            RoleName = "Super Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 11, DateTimeKind.Utc).AddTicks(1707),
                            Description = "Administrative access",
                            IsActive = true,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 11, DateTimeKind.Utc).AddTicks(1775),
                            Description = "Standard user access",
                            IsActive = true,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("Pm.Models.RolePermission", b =>
                {
                    b.Property<int>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RolePermissionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RolePermissionId = 1,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(4577),
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 2,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(5140),
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 3,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(5142),
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 4,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(5144),
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 5,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(5146),
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 6,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(5365),
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 7,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(5367),
                            PermissionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 8,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(5369),
                            PermissionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 9,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(5370),
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 10,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(5374),
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 11,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(5375),
                            PermissionId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 12,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(5377),
                            PermissionId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 13,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(5380),
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            RolePermissionId = 14,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(5382),
                            PermissionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            RolePermissionId = 15,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(5385),
                            PermissionId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            RolePermissionId = 16,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(5387),
                            PermissionId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            RolePermissionId = 17,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 13, DateTimeKind.Utc).AddTicks(5920),
                            PermissionId = 2,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Pm.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 9, 24, 6, 28, 14, 705, DateTimeKind.Utc).AddTicks(4067),
                            Email = "admin@yourdomain.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$ZVyilLKcyieXPCf5bNKoCOatxdiMkzP/nDz/pilpBEFuV6qjpQdlq",
                            RoleId = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Pm.Models.RolePermission", b =>
                {
                    b.HasOne("Pm.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pm.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Pm.Models.User", b =>
                {
                    b.HasOne("Pm.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Pm.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Pm.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
